#!/bin/bash

#SBATCH --job-name=jupyter    # Job name
#SBATCH --output=/home/agbe/MAG/CentralityFairness/EVALUATIONS_OUTPUTS/job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=6        # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=23:30:00          # Run time (hh:mm:ss) - run for one hour max

echo "Running evaluations on $(hostname):"

echo "$(hostname -I)"

module load Anaconda3
. $(conda info --base)/etc/profile.d/conda.sh
conda activate magenv

printf "PageRank:\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank /home/agbe/MAG/CentralityFairness/Evaluations/psychology.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank /home/agbe/MAG/CentralityFairness/Evaluations/economics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank /home/agbe/MAG/CentralityFairness/Evaluations/mathematics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank /home/agbe/MAG/CentralityFairness/Evaluations/chemistry.csv 


printf "\n\n\n\nPageRank05\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank05 /home/agbe/MAG/CentralityFairness/Evaluations/psychology.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank05 /home/agbe/MAG/CentralityFairness/Evaluations/economics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank05 /home/agbe/MAG/CentralityFairness/Evaluations/mathematics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank05 /home/agbe/MAG/CentralityFairness/Evaluations/chemistry.csv 


printf "\n\n\n\nPageRank05\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank05 /home/agbe/MAG/CentralityFairness/Evaluations/psychology.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank05 /home/agbe/MAG/CentralityFairness/Evaluations/economics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank05 /home/agbe/MAG/CentralityFairness/Evaluations/mathematics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None PageRank05 /home/agbe/MAG/CentralityFairness/Evaluations/chemistry.csv 

printf "\n\n\n\nInDegreeStrength\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None InDegreeStrength /home/agbe/MAG/CentralityFairness/Evaluations/psychology.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None InDegreeStrength /home/agbe/MAG/CentralityFairness/Evaluations/economics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None InDegreeStrength /home/agbe/MAG/CentralityFairness/Evaluations/mathematics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None InDegreeStrength /home/agbe/MAG/CentralityFairness/Evaluations/chemistry.csv 

printf "\n\n\n\nInDegree\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None InDegree /home/agbe/MAG/CentralityFairness/Evaluations/psychology.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None InDegree /home/agbe/MAG/CentralityFairness/Evaluations/economics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None InDegree /home/agbe/MAG/CentralityFairness/Evaluations/mathematics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None InDegree /home/agbe/MAG/CentralityFairness/Evaluations/chemistry.csv 


printf "\n\n\n\nOutDegreeStrength\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None OutDegreeStrength /home/agbe/MAG/CentralityFairness/Evaluations/psychology.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None OutDegreeStrength /home/agbe/MAG/CentralityFairness/Evaluations/economics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None OutDegreeStrength /home/agbe/MAG/CentralityFairness/Evaluations/mathematics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None OutDegreeStrength /home/agbe/MAG/CentralityFairness/Evaluations/chemistry.csv 


printf "\n\n\n\nOutDegree\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None OutDegree /home/agbe/MAG/CentralityFairness/Evaluations/psychology.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None OutDegree /home/agbe/MAG/CentralityFairness/Evaluations/economics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None OutDegree /home/agbe/MAG/CentralityFairness/Evaluations/mathematics.csv 
printf "\n\n\n\n"
time python /home/agbe/MAG/CentralityFairness/Evaluations/Evaluator.py None OutDegree /home/agbe/MAG/CentralityFairness/Evaluations/chemistry.csv 
