#!/bin/bash

#SBATCH --job-name=Mathcing    # Job name
#SBATCH --output=/home/agbe/MAG/CentralityFairness/JOB_OUTPUTS/job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=6        # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=23:30:00          # Run time (hh:mm:ss) - run for one hour max

echo "Running evaluations on $(hostname):"

echo "$(hostname -I)"

module load Anaconda3
. $(conda info --base)/etc/profile.d/conda.sh
conda activate magenv

printf "Matching economics:\n"
time python /home/agbe/MAG/CentralityFairness/matching.py "/home/agbe/MAG/CentralityFairness/Evaluations/economics2020.csv" Economics 162324750 "/home/agbe/MAG"

printf "Matching Mathematics:\n"
#time python /home/laal/MAG/CentralityFairness/matching.py /home/laal/MAG/DATA/NETWORKS/SimpleWeightMathematics2020CentralityGendered.csv Mathematics 33923547 
time python /home/agbe/MAG/CentralityFairness/matching.py "/home/agbe/MAG/CentralityFairness/Evaluations/mathematics2020.csv" Economics 33923547 "/home/agbe/MAG"

printf "Matching Psychology:\n"
#time python /home/laal/MAG/CentralityFairness/matching.py /home/laal/MAG/DATA/NETWORKS/SimpleWeightPsychology2020CentralityGendered.csv Psychology 15744967 
time python /home/agbe/MAG/CentralityFairness/matching.py "/home/agbe/MAG/CentralityFairness/Evaluations/psychology2020.csv" Economics 15744967 "/home/agbe/MAG"

printf "Matching Chemistry:\n"
#time python /home/laal/MAG/CentralityFairness/matching.py /home/laal/MAG/DATA/NETWORKS/SimpleWeightChemistry2020CentralityGendered.csv Chemistry 185592680 
time python /home/agbe/MAG/CentralityFairness/matching.py "/home/agbe/MAG/CentralityFairness/Evaluations/chemistry2020.csv" Economics 185592680 "/home/agbe/MAG"
