#!/bin/bash

#SBATCH --job-name=Fairness rND         # Job name
#SBATCH --output=/home/laal/MAG/CentralityFairness/JOB_OUTPUTS/FairJob.%j.out          # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=4            # Schedule 4 cores (includes hyperthreading)
#SBATCH --time=23:00:00              # Run time (hh:mm:ss) - run for one hour max


echo "Running on $(hostname):";

cd $PWD

module load Anaconda3;
. $(conda info --base)/etc/profile.d/conda.sh;
conda activate magenv;

python /home/laal/MAG/CentralityFairness/test_of_fairness_measures.py
